INSERT INTO users (name, age) VALUES ("Bob", 30);
INSERT INTO users (name, age) VALUES ("Dave", 27);
INSERT INTO users (name, age) VALUES ("Dolan", 31);
INSERT INTO users (name, age) VALUES ("Alex", 34);
INSERT INTO users (name, age) VALUES ("Steve", 35);
INSERT INTO users (name, age) VALUES ("Pat", 40);
INSERT INTO users (name, age) VALUES ("Doug", 23);
INSERT INTO users (name, age) VALUES ("Michael", 55);
INSERT INTO users (name, age) VALUES ("Richard", 45);
INSERT INTO users (name, age) VALUES ("Reggie", 23);
INSERT INTO users (name, age) VALUES ("Barb", 36);
INSERT INTO users (name, age) VALUES ("Betty", 25);
INSERT INTO users (name, age) VALUES ("Lisa", 29);
INSERT INTO users (name, age) VALUES ("Lois", 44);
INSERT INTO users (name, age) VALUES ("Regina", 22);
INSERT INTO users (name, age) VALUES ("Kristina", 44);
INSERT INTO users (name, age) VALUES ("Katy", 45);
INSERT INTO users (name, age) VALUES ("Kelly", 32);
INSERT INTO users (name, age) VALUES ("Elle", 23);
INSERT INTO users (name, age) VALUES ("Amanda", 33);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Rocket", "Travel", 10000000, "11/1/2018","11/1/2023");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cars", "Travel", 110000, "11/2/2018","1/6/2024");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Trees", "Environment", 2000000, "11/3/2018","12/1/2030");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Water", "Environment", 100000000, "11/4/2018","2/1/2040");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fame", "Social", 25000, "11/5/2018","11/30/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Youtuber", "Social", 15000, "11/6/2018","1/15/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Influencer", "Social", 5000, "11/7/2018","3/23/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Injury", "Health", 1000000, "11/8/2018","12/31/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cancer", "Health", 2000000000, "11/9/2018","1/1/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Accident", "Health", 300000, "11/10/2018","2/1/2019");

INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (103, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (105, 17, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 11, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 10, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 18, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 19, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 14, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (105, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 13, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13, 17, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (19, 11, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 10, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (105, 9, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 19, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (103, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (64, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 10, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 11, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (105, 1, 8);
